version: '3.9'  # Updated to the latest Compose specification

services:
  nss_api:
    build:
      context: ./backend
      dockerfile: ../build/Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=nss
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  nss_ui:
    build:
      context: ./frontend
      dockerfile: ../build/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
    #command: tail -f /dev/null
    command: npm start

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nss
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
