# Generated by Django 4.2.11 on 2024-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'College Admin'), ('leader', 'Leader'), ('volunteer', 'Volunteer')], default='Volunteer', max_length=20),
        ),
    ]
