# Generated by Django 4.2.11 on 2024-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=20),
        ),
    ]
