# Generated by Django 4.2.11 on 2024-05-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nss_events', '0001_initial'),
        ('nss_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_profile.volunteerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('volunteer', 'event')},
        ),
    ]
