# Generated by Django 4.2.11 on 2024-06-30 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nss_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nss_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_profile.college'),
        ),
        migrations.AddField(
            model_name='eventcomments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_events.events'),
        ),
        migrations.AddField(
            model_name='eventcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_events.events'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_profile.volunteer'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('volunteer', 'event')},
        ),
    ]
