# Generated by Django 4.2.11 on 2024-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='upcoming'),
        ),
    ]
