# Generated by Django 4.2.11 on 2024-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nss_profile', '0002_alter_volunteerprofile_role'),
        ('nss_events', '0002_rename_date_events_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='credit_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')]),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_events.events')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_profile.volunteerprofile')),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('volunteer', 'event')},
            },
        ),
    ]
