# Generated by Django 4.2.11 on 2024-05-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss_events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
    ]
