# Generated by Django 4.2.11 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Deleted', 'Deleted'), ('Completed', 'Completed')], default='Open'),
        ),
    ]
